### ISSUE TITLE
Unable to sync with a private subrepo

### ISSUE THREAD

**Issue by KlausPopp** [mheap/submodule-sync-action#1]
I'm trying to sync with a simple private submodule. The submodule1 exists in the upper repo and the submodule1 has not been changed yet. I get this error:

token is a personal access token I've create
```
Run mheap/submodule-sync-action@v1
  with:
    token: ***
    path: submodule1
    ref: main
    pr_branch: automated-submodule-update
    target_branch: main
(node:1504) UnhandledPromiseRejectionWarning: HttpError: Not Found
    at /home/runner/work/_actions/mheap/submodule-sync-action/v1/dist/index.js:3773:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async action (/home/runner/work/_actions/mheap/submodule-sync-action/v1/dist/index.js:48:25)
(node:1504) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1504) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
What I'm doing wrong?

**Comment by mheap** [comment]
Are you using `${{ secrets.GITHUB_TOKEN }}` in `token`, or a Personal Access Token?

**Comment by KlausPopp** [comment]
A Personal Access token

**Comment by mheap** [comment]
Hrm, that's odd. Does the PAT have the `all repos` scope, or just public repos?

The action should work fine with private submodules when provided with a PAT

**Comment by KlausPopp** [comment]
Yes: Here are the settings of my token:
![grafik](https://user-images.githubusercontent.com/15684373/150200732-b56e1df2-1d8a-4aa4-8fd1-bc49b80ba6d8.png)

Another strange this is: Although I get the exception mentioned in my first message, the action is marked as "succeeded" (green)

**Comment by KlausPopp** [comment]
Here is the workflow file:
```
name: Submodule Sync
on:
  schedule:
    - cron: "15 */4 * * *"
  workflow_dispatch: ~

jobs:
  submodule-sync:
    name: Submodule Sync
    runs-on: ubuntu-latest
    steps:
      - name: Submodule1 Sync
        uses: mheap/submodule-sync-action@v1
        with:
          token: ${{ secrets.PAT_TOKEN }}
          path: submodule1
          ref: main
          pr_branch: automated-submodule-update
          target_branch: main
      - name: Submodule2 Sync
        uses: mheap/submodule-sync-action@v1
        with:
          token: ${{ secrets.PAT_TOKEN }}
          path: submodule2
          ref: main
          pr_branch: automated-submodule-update
          target_branch: main
```
